# Introduction to Python

Python is a **high-level**, **general-purpose**, **interpreted** programming language. It is **dynamically type-checked** and **garbage-collected**. It supports multiple programming paradigms, including **structured (particularly procedural)**, **object-oriented** and **functional** programming.

## Installation

### Windows

#### Install Python

1. Download a Windows installer for a stable release of Python from [Python Downloads](https://www.python.org/downloads/windows/).
2. Run the installer.
3. Check the option "Add python.exe to PATH".
4. Choose "Install Now".
5. Verify the installation with `python --version`.

#### Create a Virtual Environment

1. Open Command Prompt.
2. Navigate to your project directory with `cd <project_directory>`.
3. Create a virtual environment with `python -m venv .venv`.
4. Activate the virtual environment with `.venv\Scripts\activate`.
5. Now, the prompt should start with `(.venv)`.

#### Install Jupyter Notebook

1. With the virtual environment active, install Jupyter with `pip install jupyter`.
2. Start Jupyter Notebook with `jupyter notebook`.
3. A browser will open with the notebook interface.

Notes:
- You can choose another name for the virtual environment instead of `.venv`.
- You can exit the virtual environment with `deactivate`.

## Variables

Python is a **dynamically typed** programming language, meaning that the type of a variable is determined at runtime, not beforehand. That's why we don't declare the type when initializing a variable.

The most common numeric types in Python are `int` and `float`. The `int` type represents integers, i.e., whole numbers, positive or negative, without a decimal point. The `float` type represents real numbers with decimal points or in exponential form.

In [1]:
int_var = 7

In [2]:
float_var = 10.74

We can check the type of a variable with the built-in function `type()`.

In [7]:
type(int_var)

int

In [8]:
type(float_var)

float

The boolean type in Python representing truth values is `bool`. It can be either `True` or `False`.

In [9]:
bool_var = True

In [10]:
type(bool_var)

bool

In Python, there is no `character` type, unlike in other languages. The `str` type can be used both to represent characters and strings of characters. We can use both single and double quotes to initialize a string.

In [11]:
string1 = "A"
string2 = "Hello, world!"
string3 = "Welcome!"

To print the value of a variable, we can use the built-in function `print()`. It prints the string representation of the variable, followed by a new line, to the standard output.

In [12]:
print(int_var)
print(float_var)
print(bool_var)
print(string1)

7
10.74
True
A


We can provide multiple values to the `print()` function. It will print them separated with a space and a new line at the end.

In [13]:
print(int_var, float_var, bool_var, string1)

7 10.74 True A


To cast a variable from one type to another, we can use the name of the type as a function, e.g., `int()`, `float()`, `bool()`, `str()`, etc.

In [14]:
var1 = 15.2

In [15]:
int(var1)

15

In [16]:
var2 = "10"

In [17]:
int(var2)

10

We can also assign values to multiple variables at the same time.

In [18]:
x, y, z = "world", 1, 85.33

In Python, `NoneType` is the data type for the special value `None`. `None` represents the absence of a value or a null reference. It is a unique and immutable object in Python, meaning there is only one instance of `None` in memory.

In [19]:
empty_var = None

In [20]:
type(empty_var)

NoneType

To check if a variable is `None`, we can use the `is` operator.

In [21]:
empty_var is None

True

In [22]:
int_var is None

False

## Operators and Conditions

The relational operators are: equal to (`==`), not equal to (`!=`), less than (`<`), less than or equal to (`<=`), greater than (`>`), and greater than or equal to (`>=`).

In [19]:
if int_var < 10:
    print("The value of the variable is less than 10.")

The value of the variable is less than 10.


In [20]:
if int_var < 5:
    print("The value of the variable is less than 5.")
else:
    print("The value of the variable is greater than or equal to 5.")

The value of the variable is greater than or equal to 5.


In [21]:
if int_var < 5:
    print("The value of the variable is less than 5.")
elif int_var < 10:
    print("The value of the variable is greater than or equal to 5 and less than 10.")
else:
    print("The value of the variable is greater than or equal to 10.")

The value of the variable is greater than or equal to 5 and less than 10.


In Python, the logical operators are: and (`and`), or (`or`) and not (`not`).

The `and` and `or` operators exhibit short-circuiting behavior. For `and`, if the first operand is `False`, the second operand is not evaluated because the overall result will already be `False`. For `or`, if the first operand is `True`, the second operand is not evaluated because the overall result will already be `True`.

In [22]:
if int_var < 10 or float_var > 30:
    print("Success!")

Success!


In [23]:
if int_var < 10 and float_var > 30:
    print("Success")
else:
    print("Error!")

Error!


In [24]:
if not int_var < 5:
    print("The value of the variable is greater than or equal to 5.")

The value of the variable is greater than or equal to 5.


## Data Structures

### Lists

Lists are ordered, mutable sequences of elements.

In [23]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The elements in a list can be from different types.

In [24]:
list2 = [1, "Hello, world!", 17.2, True]

They can contain duplicates.

In [25]:
list3 = [1, 2, 2, 3, 3, 4, 4, 4]

We can get the length of a list using the built-in function `len()`.

In [26]:
len(list1)

10

In [27]:
len(list2)

4

In [28]:
len(list3)

8

We can access elements of a list using zero-based indexing.

In [29]:
list1[0]

1

In [32]:
list2[3]

True

We can use negative indices to access elements from the end of a list.

In [33]:
list1[-1]

10

In [34]:
list2[-2]

17.2

We can slice a list using the built-in function `slice()` or the operand `:`. The syntax is `slice(start, stop, step)` or `start:stop:step`.

In [35]:
list1[slice(2, 5)]

[3, 4, 5]

In [36]:
list1[2:5]

[3, 4, 5]

In [37]:
list1[0:10:2]

[1, 3, 5, 7, 9]

In [38]:
list3[1:-1]

[2, 2, 3, 3, 4, 4]

*Hack: To reverse a list, we can use `[::-1]`.*

In [39]:
list1[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

Note: Slicing a list returns a copy of that segment of the list. We can use the slicing notation to create a copy of a list using `[:]`.

In [34]:
list2_copy = list2[:]

In [35]:
list2_copy

[1, 'Hello, world!', 17.2, True]

To check if an element exists in a list, we can use the operator `in`.

In [36]:
if 1 in list1:
    print("The list1 contains 1.")

The list1 contains 1.


To assign a specific value to an element in a list, we can use indexing or slicing with the `=` operator.

In [37]:
list1[0] = 10

In [38]:
list1

[10, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
list1[1:3] = [9, 8]

In [46]:
list1

[10, 9, 8, 4, 5, 6, 7, 8, 9, 10]

To insert a element at a specific position in a list, we can use the `.insert()` method.

In [47]:
list3.insert(3, "world")

In [48]:
list3

[1, 2, 2, 'world', 3, 3, 4, 4, 4]

To add an element to the end of a list, we can use the `.append()` method.

In [49]:
list3.append("a")

In [50]:
list3

[1, 2, 2, 'world', 3, 3, 4, 4, 4, 'a']

To add multiple elements to the end of a list, we can use the `.extend()` method.

In [39]:
list3.extend(["b", "c"])

In [40]:
list3

[1, 2, 2, 3, 3, 4, 4, 4, 'b', 'c']

To remove the first occurence of an element in a list, we can use the `.remove()` method.

In [41]:
list3.remove(3)

In [42]:
list3

[1, 2, 2, 3, 4, 4, 4, 'b', 'c']

To remove and return an element at a specific position, we can use the `.pop()` method. *The default index is -1.*

In [45]:
list3.pop()

4

In [46]:
list3

[1, 2, 2, 3, 4, 4]

In [57]:
list3.pop(3)

'world'

In [58]:
list3

[1, 2, 2, 3, 4, 4, 4, 'a', 'b']

List comprehension in Python offers a concise and efficient way to create new lists based on existing iterables (like lists, tuples, strings, etc.). It provides a more compact and often more readable alternative to traditional for loops for list creation, transformation, and filtering.

In [47]:
new_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [48]:
[2 * element for element in new_list]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [49]:
[2 * element for element in new_list if element % 2 == 0]

[4, 8, 12, 16, 20]

In [50]:
[2 * element if element % 2 == 0 else 0 for element in new_list]

[0, 4, 0, 8, 0, 12, 0, 16, 0, 20]

### Tuples

Tuples are ordered, immutable sequences of elements.

In [51]:
tuple1 = (1, 2, 3)

In [52]:
tuple2 = ("a", "b", "c", "world", 100)

We cannot change a tuple directly, because they are immutable.

In [53]:
tuple1[0] = "A"

TypeError: 'tuple' object does not support item assignment

In [54]:
new_tuple = ("hello",) + tuple2

In [55]:
new_tuple

('hello', 'a', 'b', 'c', 'world', 100)

### Sets

Sets are unordered collections of unique elements.

In [56]:
fruits = {"apple", "banana", "orange", "apple"}

In [57]:
fruits

{'apple', 'banana', 'orange'}

In [58]:
fruits.add("banana")

In [59]:
fruits

{'apple', 'banana', 'orange'}

In [62]:
fruits[0]

TypeError: 'set' object is not subscriptable

Set comprehension, similar to list comprehensions, allows for the construction of sets by iterating over an iterable and optionally applying transformations or filters to its elements.

In [63]:
new_set = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [70]:
{element % 3 for element in new_set}

{0, 1, 2}

In [64]:
{element % 3 for element in new_set if element % 3 == 0}

{0}

In [65]:
{element % 3 if element % 3 == 0 else -1 for element in new_set}

{-1, 0}

### Dictionaries

Dictionaries are unordered collections of key-value pairs.

- A key in a dictionary can be any value with an immutable type, e.g., `int`, `float`, `bool`, `str`, `tuple`, etc.
- There is no restrictions for the values in a dictionary.

In [66]:
person = {
    "name": "Dimitar",
    "surname": "Peshevski",
    "age": 24,
    "height": 185,
}

In [74]:
print(person)

{'name': 'Dimitar', 'surname': 'Peshevski', 'age': 24, 'height': 185}


In [75]:
len(person)

4

In [67]:
person.keys()

dict_keys(['name', 'surname', 'age', 'height'])

In [77]:
person.values()

dict_values(['Dimitar', 'Peshevski', 24, 185])

In [68]:
person["is_assistant"] = True

In [69]:
print(person)

{'name': 'Dimitar', 'surname': 'Peshevski', 'age': 24, 'height': 185, 'is_assistant': True}


In [70]:
"name" in person.keys()

True

In [71]:
courses = [
    "Data Science",
    "Probability and Statistics",
    "Parallel and Distributed Processing",
]

In [72]:
person["courses"] = courses

In [73]:
print(person)

{'name': 'Dimitar', 'surname': 'Peshevski', 'age': 24, 'height': 185, 'is_assistant': True, 'courses': ['Data Science', 'Probability and Statistics', 'Parallel and Distributed Processing']}


In [76]:
car = {
    "brand": "Mazda",
    "model": "CX30",
    "hp": 250,
}

In [77]:
person["car"] = car

In [78]:
print(person)

{'name': 'Dimitar', 'surname': 'Peshevski', 'age': 24, 'height': 185, 'is_assistant': True, 'courses': ['Data Science', 'Probability and Statistics', 'Parallel and Distributed Processing'], 'car': {'brand': 'Mazda', 'model': 'CX30', 'hp': 250}}


In [79]:
person.pop("car")

{'brand': 'Mazda', 'model': 'CX30', 'hp': 250}

Dictionary comprehension, similar to list and set comprehension, offers a more readable and often faster alternative to traditional for loops for constructing dictionaries from iterables.

In [80]:
new_list = ["abc", "hello", "world"]

In [81]:
{element: len(element) for element in new_list}

{'abc': 3, 'hello': 5, 'world': 5}

In [82]:
{element: len(element) for element in person}

{'name': 4,
 'surname': 7,
 'age': 3,
 'height': 6,
 'is_assistant': 12,
 'courses': 7}

## Loops

In [83]:
list1 = [1, "world", True, 10.1, [1, 2, 3]]

In [84]:
for element in list1:
    print(element)

1
world
True
10.1
[1, 2, 3]


In [88]:
for index in range(len(list1)):
    print(index, "-->", list1[index])

0 --> 1
1 --> world
2 --> True
3 --> 10.1
4 --> [1, 2, 3]


In [94]:
for index in range(0, len(list1), 2):
    print(index, "-->", list1[index])

0 --> 1
2 --> True
4 --> [1, 2, 3]


In [95]:
index = 0
while index < len(list1):
    print(index, "-->", list1[index])
    index += 1

0 --> 1
1 --> world
2 --> True
3 --> 10.1
4 --> [1, 2, 3]


## Functions

In [93]:
def full_name(name, surname):
    return " ".join([name, surname])

In [94]:
full_name("Dimitar", "Peshevski")

'Dimitar Peshevski'

In [99]:
def welcome(name, surname):
    result = "Hello" + name + " " + surname
    print(result)

In [100]:
welcome("Dimitar", "Peshevski")

HelloDimitar Peshevski


## NumPy

NumPy, short for Numerical Python, is a fundamental Python library for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a comprehensive collection of high-level mathematical functions to operate on these arrays.

To install NumPy run `pip install numpy`.

In [3]:
import numpy as np

### 1D Arrays

In [5]:
array1 = np.array([1, 2, 3, 4, 5])

In [6]:
array1

array([1, 2, 3, 4, 5])

In [7]:
array2 = np.array([1, 2, 3, True, "world"])

In [8]:
array2

array(['1', '2', '3', 'True', 'world'], dtype='<U21')

In [10]:
array1.ndim

1

In [11]:
array2.shape

(5,)

In [21]:
array2[-1]

np.str_('world')

In [108]:
array2[-1].item()

'world'

In [31]:
array1[0].item()

1

In [110]:
array1[0].item()

1

### 2D Arrays

In [68]:
matrix = np.array(
    [
        [1, 2, 3, 4, 5,1],
        [6, 7, 8, 9, 10,100],
    ]
)

In [44]:
matrix.ndim

2

In [45]:
matrix.shape

(2, 5)

In [46]:
array1 + matrix

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [56]:
array1 * matrix

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [57]:
np.sum(matrix)

np.int64(55)

In [92]:
np.multiply(array1, matrix)

ValueError: operands could not be broadcast together with shapes (5,) (2,6) 

In [114]:
matrix.reshape(3,4)

array([[  1,   2,   3,   4],
       [  5,   1,   6,   7],
       [  8,   9,  10, 100]])

## Pandas

Pandas is an open-source Python library designed for data manipulation and analysis. It provides powerful and flexible data structures, primarily the DataFrame and Series, which are well-suited for working with structured data, similar to tables in a database or spreadsheets.

To install Pandas run `pip install pandas`.

In [116]:
import pandas as pd

In [117]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [25, 30, 35, 40, 28],
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
}

In [118]:
df = pd.DataFrame(data)

In [124]:
df

name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   28      Phoenix

In [125]:
df.to_csv("data.csv")

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   age     5 non-null      int64 
 2   city    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
